### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by ghost** [hauntek/python-ngrokd#3]
设置了域名后，运行报错：
Traceback (most recent call last):
File "ngrokd.py", line 126, in 
threading.Thread(daemon=True, target = service, args = (SERVERHOST, SERVERPORT)).start() # 鏈嶅姟鍚敤,SERVICE
TypeError: init() got an unexpected keyword argument 'daemon'

去掉daemon参数，接着报错：
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 764, in run
self.__target(*self.__args, **self.__kwargs)
File "ngrokd.py", line 97, in service
from connt import HKServer
ImportError: No module named connt

Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 764, in run
self.__target(*self.__args, **self.__kwargs)
File "ngrokd.py", line 72, in http_service
from connt import HHServer
ImportError: No module named connt

Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 764, in run
self.__target(*self.__args, **self.__kwargs)
File "ngrokd.py", line 44, in https_service
from connt import HHServer
ImportError: No module named connt

当我改成import connt后
[2017/06/26 08:52:16] [ERROR] [root] [ngrok:80] [Errno -2] Name or service not known
[2017/06/26 08:52:16] [ERROR] [root] [ngrok:4443] [Errno -2] Name or service not known
[2017/06/26 08:52:16] [ERROR] [root] [ngrok:443] [Errno -2] Name or service not known

无法成功运行

**Comment by hauntek** [comment]
建议使用python2.7.9 或 python3.1以上版本

**Comment by ghost** [comment]
Python 2.7.13
首先还是报错：Traceback (most recent call last):
  File "ngrokd.py", line 126, in <module>
    threading.Thread(daemon=True, target = service, args = (SERVERHOST, SERVERPORT)).start() # 鏈嶅姟鍚敤,SERVICE
TypeError: __init__() got an unexpected keyword argument 'daemon'

删除daemon=True，依旧报错
[2017/06/26 15:58:15] [ERROR] [root] [ngrok:80] [Errno -2] Name or service not known
[2017/06/26 15:58:15] [ERROR] [root] [ngrok:4443] [Errno -2] Name or service not known
[2017/06/26 15:58:15] [ERROR] [root] [ngrok:443] [Errno -2] Name or service not known

**Comment by hauntek** [comment]
你看下是不是编码问题或者你设置的服务IP

**Comment by ghost** [comment]
原因不详，ngrok,frp我都直接可以用。。。
另外，我想问下，为何2.7.5的自带python版本不能用？是用了什么新特性吗。

**Comment by hauntek** [comment]
这个服务端项目目前还在写，对python2系列还没优化代码兼容，我是按照python3的规范写的，服务端我建议还是用go的版本

**Comment by ghost** [comment]
好的
